### ISSUE TITLE
Check if `node_modules` exists in root folder when running the project

### ISSUE THREAD

**Issue by catalinmiron** [exponent/xdl#1]
Add an extra step for checking `node_modules` existance. I had this problem and this wasn't in the log.

A solution to this is adding `Doctor._validateNodeModulesAsync()` right after https://github.com/exponentjs/xdl/blob/master/src/Project.js#L96. We can also use https://github.com/exponentjs/xdl/blob/2b47e63a7897b5a578b6b1d7a66b87a0f86be2a7/src/project/Doctor.js#L148

**Comment by dikaiosune** [comment]
@jesseruder is this still a problem? IIRC you pushed a fix for this

**Comment by jesseruder** [comment]
Yeah should be fixed
